language: node_js
node_js:
  - "node"
notifications:
  email: false
install:
  - npm install
  - cd nin/frontend && npm install && cd -
script:
  - cd nin/backend && ../../node_modules/.bin/eslint .
  - cd ../frontend && make lint
